[package]
name = "configuration"
version = "0.0.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
mote-api = { path = "../mote-api" }

wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.6.5"
anyhow = "1.0"
